name: decor_ride
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # arcore_flutter_plugin: ^0.1.0
  arcore_flutter_plugin:
    git:
      url: https://github.com/tonyhart7/arcore_flutter_plugin_updated.git
  ar_flutter_plugin:
    git:
      url: https://github.com/alainjr10/ar_flutter_plugin.git
  vector_math: ^2.1.4
  model_viewer_plus: ^1.6.1

  #NAVIGATION AND STATE MANAGEMENT
  go_router: ^9.0.3
  flutter_riverpod: ^2.3.6

  #FIREBASE
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.0

  #OFFLINE DB
  isar: ^3.1.0+1

  #Camera
  camera_android_camerax: ^0.5.0+9
  camera: ^0.10.5+2

  #Utils
  freezed_annotation: ^2.4.1
  flutter_screenutil: ^5.8.4

  path_provider: ^2.0.15
  firebase_storage: ^11.2.5
  fluttertoast: ^8.2.2
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.8
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  riverpod_lint: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/furniture_assets/
    - assets/3d_models/
    - assets/3d_models/gltf/
    - assets/
    - assets/AndroidRobot.gif
    - assets/ArcticFox.gif
    - assets/TocoToucan.gif
    - assets/fox_face_mesh_texture.png
    - assets/prova_texture.png
    - assets/venom.jpg
    - assets/venom_with_eyes.jpg
    - assets/earth.jpg
    - assets/earth_augmented_image.jpg
    - assets/copertina.jpg
    - assets/umano_digitale.png
    - assets/myimages.imgdb
    - assets/topolino.jpg
