name: decor_ride
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # arcore_flutter_plugin: ^0.1.0
  arcore_flutter_plugin:
    git:
      url: https://github.com/tonyhart7/arcore_flutter_plugin_updated.git
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/AndroidRobot.gif
    - assets/ArcticFox.gif
    - assets/TocoToucan.gif
    - assets/fox_face_mesh_texture.png
    - assets/prova_texture.png
    - assets/venom.jpg
    - assets/venom_with_eyes.jpg
    - assets/earth.jpg
    - assets/earth_augmented_image.jpg
    - assets/copertina.jpg
    - assets/umano_digitale.png
    - assets/myimages.imgdb
    - assets/topolino.jpg
