// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdfvJCc3-DGW-ZJebhGt71D9IWEFCwY_A',
    appId: '1:747068734693:web:b083ad847196822adb280c',
    messagingSenderId: '747068734693',
    projectId: 'decor-ride',
    authDomain: 'decor-ride.firebaseapp.com',
    storageBucket: 'decor-ride.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGNg3Ze25oU5iHnQbkAxdYh0hnRJjMaoI',
    appId: '1:747068734693:android:3289b68014c4615cdb280c',
    messagingSenderId: '747068734693',
    projectId: 'decor-ride',
    storageBucket: 'decor-ride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0e8r2CEkBadXUcsdXM3xlPXiT9gXdvns',
    appId: '1:747068734693:ios:8fb5a8c6707cc267db280c',
    messagingSenderId: '747068734693',
    projectId: 'decor-ride',
    storageBucket: 'decor-ride.appspot.com',
    iosClientId: '747068734693-ksiunsdunpjgn602hhr92n43gibe3jfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.decorRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0e8r2CEkBadXUcsdXM3xlPXiT9gXdvns',
    appId: '1:747068734693:ios:f064db069a084774db280c',
    messagingSenderId: '747068734693',
    projectId: 'decor-ride',
    storageBucket: 'decor-ride.appspot.com',
    iosClientId: '747068734693-rkoguvs536dkn5fprojbeakh60qoe1jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.decorRide.RunnerTests',
  );
}
